RESOLUTION = (2560, 1440)
WIDTH, HEIGHT = RESOLUTION
FPS = 165
FULLSCREEN = True
WINDOW_NAME = "CONWAYS GAME OF LIFE"

GRID_SIZE = 40
GRID_WIDTH = 1

GRID_X = WIDTH // GRID_SIZE
GRID_Y = HEIGHT // GRID_SIZE
